apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-bridge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-bridge
    app.kubernetes.io/part-of: segment-bridge
  name: segment-bridge
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: segment-bridge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: segment-bridge
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/segment-bridge/segment-bridge@sha256:ec068d860943a3a54d6e22798a70acf8bf2f2b65b9136396a62ae882ba68a2ac
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
