apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-bridge
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/segment-bridge/segment-bridge@sha256:a25549ad4b42fc74c2d7cf2a9440514e8cdf80e2f1af43f615d037f1dd7ddbad
        name: container-image
        resources: {}
status: {}
