apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-bridge
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-o11y-tenant/segment-bridge/segment-bridge@sha256:ec068d860943a3a54d6e22798a70acf8bf2f2b65b9136396a62ae882ba68a2ac
        name: container-image
        resources: {}
status: {}
